[book]
title = "Internal Developer Platform (IDP) Book"
authors = ["Shahrooz Aghili","Anais Urlichs"]
language = "en"
multilingual = false
src = "src"

[output.html]
mathjax-support = true
site-url = "/"
git-repository-url = "https://github.com/roozy-io/idp"